apiVersion: apps/v1
kind: Deployment
metadata:
  name: pc4-app-nonroot
  labels:
    app: pc4-app-nonroot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pc4-app-nonroot
  template:
    metadata:
      labels:
        app: pc4-app-nonroot
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        fsGroup: 1000
      containers:
      - name: pc4-app-nonroot
        image: pc4-app-nonroot:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: app-tmp
          mountPath: /app-nonroot/tmp
      volumes:
      - name: tmp
        emptyDir: {}
      - name: app-tmp
        emptyDir: {}
